# Decision Tree Classifier

In [52]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from matplotlib.legend_handler import HandlerLine2D
from sklearn.model_selection import train_test_split

df = pd.read_csv('https://raw.githubusercontent.com/marvv0905/ISOM3360-project/refs/heads/main/datasets/shopping_dataset_dummyCoded.csv')

### Variable set up
- Encode target variable, since cannot use binary to represent due to multi-classed values (Store / Hybrid / Online)
- Splitting features and target variable
- Splitting into training/ test set

In [56]:
#Encoding target variable
encoder = LabelEncoder()

targ = 'shopping_preference'
features = [col for col in df.columns if col != targ]

x = df[features]
y = encoder.fit_transform(df[targ])

#stratify used due to unbalanced dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state = 42)


print(dict(zip(encoder.classes_, encoder.transform(encoder.classes_))))
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)


{'Hybrid': 0, 'Online': 1, 'Store': 2}
(8252, 28) (3537, 28) (8252,) (3537,)


### Base model

In [57]:
#fit model with train data
base_model = DecisionTreeClassifier()
base_model.fit(x_train, y_train)

dec_tree = base_model.tree_
print(dec_tree.node_count)

fig = plt.figure(figsize=(100,100))
_ = tree.plot_tree(base_model,
                   feature_names = features,
                   class_names= list(encoder.classes_),
                   filled=True)

635


In [63]:
pred_test = base_model.predict(x_test)
print(f'accuracy = {accuracy_score(y_test, pred_test, normalize=True, sample_weight=None)}')
print(classification_report(y_test, pred_test, target_names=encoder.classes_))
print('confusion matrix', '\n', confusion_matrix(y_test, pred_test))

pred_train = base_model.predict(x_train)
print(f'Training data accuracy = {accuracy_score(y_train, pred_train, normalize=True, sample_weight=None)}')


accuracy = 0.9267741023466214
              precision    recall  f1-score   support

      Hybrid       0.18      0.21      0.19       111
      Online       0.79      0.79      0.79       353
       Store       0.97      0.97      0.97      3073

    accuracy                           0.93      3537
   macro avg       0.65      0.66      0.65      3537
weighted avg       0.93      0.93      0.93      3537

confusion matrix 
 [[  23   39   49]
 [  46  279   28]
 [  61   36 2976]]
Training data accuracy = 1.0
